## Merge 3L-free and 3R-free data for treemix

In [1]:
%run local_imports.ipynb

In [43]:
treemix_3L = pd.read_csv('/home/randomx/Dropbox/Ag1000G_carlo/paper1/scripts/treemix-data/phase2_with_outgroups/3L_free/3L-free.allele_counts.txt.gz', sep = ' ')
treemix_3L

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"41,115","46,104","16,168","41,101","80,514","13,35","33,105","24,86","1,23","48,82",...,"8,72","5,13","86,96","1,95","33,191","0,24","1,0","8,0","20,0","20,0"
1,"91,65","86,64","115,69","72,70","391,203","30,18","105,33","54,56","13,11","102,28",...,"49,31","10,8","139,43","28,68","154,70","0,24","1,0","8,0","5,15","20,0"
2,"144,12","117,33","166,18","120,22","558,36","33,15","132,6","91,19","21,3","118,12",...,"79,1","16,2","172,10","54,42","183,41","24,0","1,0","8,0","20,0","20,0"
3,"34,122","42,108","81,103","75,67","277,317","3,45","82,56","52,58","11,13","85,45",...,"35,45","5,13","91,91","26,70","104,120","24,0","1,0","8,0","20,0","20,0"
4,"89,67","58,92","115,69","45,97","331,263","45,3","48,90","48,62","9,15","52,78",...,"46,34","12,6","77,105","54,42","155,69","24,0","1,0","8,0","20,0","20,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27604,"88,68","60,90","93,91","39,103","311,283","42,6","94,44","47,63","10,14","52,78",...,"32,48","11,7","67,115","72,24","99,125","24,0","0,1","0,8","0,20","0,20"
27605,"104,52","139,11","176,8","136,6","564,30","43,5","128,10","106,4","23,1","121,9",...,"77,3","16,2","176,6","92,4","206,18","24,0","1,0","8,0","20,0","20,0"
27606,"134,22","106,44","102,82","85,57","300,294","21,27","68,70","68,42","14,10","70,60",...,"40,40","10,8","97,85","37,59","119,105","0,24","0,1","0,8","0,20","20,0"
27607,"27,129","74,76","74,110","81,61","234,360","27,21","32,106","44,66","12,12","61,69",...,"28,52","6,12","101,81","35,61","104,120","24,0","1,0","0,8","0,20","0,20"
27608,"143,13","137,13","141,43","134,8","458,136","39,9","121,17","103,7","18,6","123,7",...,"63,17","13,5","159,23","72,24","170,54","14,10","1,0","8,0","20,0","20,0"

In [44]:
treemix_3R = pd.read_csv('/home/randomx/Dropbox/Ag1000G_carlo/paper1/scripts/treemix-data/phase2_with_outgroups/3R_free/3R-free.allele_counts.txt.gz', sep = ' ')
treemix_3R

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"118,38","106,44","51,133","83,59","174,420","22,26","27,111","58,52","10,14","31,99",...,"26,54","12,6","44,138","89,7","50,174","0,24","0,1","0,8","0,20","0,20"
1,"5,151","109,41","78,106","91,51","253,341","22,26","23,115","73,37","7,17","65,65",...,"25,55","4,14","88,94","30,66","77,147","0,24","0,1","0,8","0,20","0,20"
2,"29,127","46,104","70,114","40,102","231,363","26,22","14,124","31,79","13,11","32,98",...,"40,40","11,7","34,148","37,59","77,147","0,24","0,1","0,8","0,20","0,20"
3,"113,43","117,33","161,23","114,28","513,81","3,45","121,17","88,22","18,6","115,15",...,"75,5","14,4","162,20","37,59","179,45","24,0","0,1","8,0","20,0","20,0"
4,"84,72","103,47","104,80","106,36","331,263","17,31","75,63","87,23","16,8","79,51",...,"50,30","11,7","106,76","89,7","122,102","24,0","1,0","8,0","20,0","20,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40182,"86,70","58,92","48,136","62,80","155,439","14,34","29,109","58,52","9,15","37,93",...,"25,55","3,15","72,110","43,53","74,150","0,24","0,1","0,8","0,20","0,20"
40183,"126,30","141,9","165,19","137,5","549,45","37,11","122,16","109,1","23,1","121,9",...,"74,6","17,1","172,10","55,41","211,13","24,0","0,1","0,8","20,0","20,0"
40184,"12,144","87,63","85,99","68,74","280,314","7,41","68,70","64,46","7,17","106,24",...,"26,54","3,15","138,44","43,53","112,112","2,22","1,0","0,8","20,0","20,0"
40185,"94,62","116,34","119,65","100,42","342,252","26,22","78,60","79,31","16,8","93,37",...,"54,26","10,8","110,72","77,19","119,105","2,22","0,1","8,0","20,0","20,0"
40186,"34,122","76,74","48,136","86,56","195,399","20,28","54,84","67,43","6,18","88,42",...,"19,61","6,12","125,57","84,12","56,168","4,20","0,1","8,0","20,0","20,0"

In [45]:
chrom_3 = pd.concat([treemix_3L, treemix_3R])
chrom_3

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"41,115","46,104","16,168","41,101","80,514","13,35","33,105","24,86","1,23","48,82",...,"8,72","5,13","86,96","1,95","33,191","0,24","1,0","8,0","20,0","20,0"
1,"91,65","86,64","115,69","72,70","391,203","30,18","105,33","54,56","13,11","102,28",...,"49,31","10,8","139,43","28,68","154,70","0,24","1,0","8,0","5,15","20,0"
2,"144,12","117,33","166,18","120,22","558,36","33,15","132,6","91,19","21,3","118,12",...,"79,1","16,2","172,10","54,42","183,41","24,0","1,0","8,0","20,0","20,0"
3,"34,122","42,108","81,103","75,67","277,317","3,45","82,56","52,58","11,13","85,45",...,"35,45","5,13","91,91","26,70","104,120","24,0","1,0","8,0","20,0","20,0"
4,"89,67","58,92","115,69","45,97","331,263","45,3","48,90","48,62","9,15","52,78",...,"46,34","12,6","77,105","54,42","155,69","24,0","1,0","8,0","20,0","20,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40182,"86,70","58,92","48,136","62,80","155,439","14,34","29,109","58,52","9,15","37,93",...,"25,55","3,15","72,110","43,53","74,150","0,24","0,1","0,8","0,20","0,20"
40183,"126,30","141,9","165,19","137,5","549,45","37,11","122,16","109,1","23,1","121,9",...,"74,6","17,1","172,10","55,41","211,13","24,0","0,1","0,8","20,0","20,0"
40184,"12,144","87,63","85,99","68,74","280,314","7,41","68,70","64,46","7,17","106,24",...,"26,54","3,15","138,44","43,53","112,112","2,22","1,0","0,8","20,0","20,0"
40185,"94,62","116,34","119,65","100,42","342,252","26,22","78,60","79,31","16,8","93,37",...,"54,26","10,8","110,72","77,19","119,105","2,22","0,1","8,0","20,0","20,0"
40186,"34,122","76,74","48,136","86,56","195,399","20,28","54,84","67,43","6,18","88,42",...,"19,61","6,12","125,57","84,12","56,168","4,20","0,1","8,0","20,0","20,0"

In [8]:
chrom_3.to_csv('/home/randomx/3_complete.txt',index=False, sep=" ")

-----------------------------

# Christyi only

*** Workaround ***

## Chromosome 3
## Euchromatic

In [46]:
chrom_3_chri = chrom_3.drop(chrom_3.columns[[16,18,19,20]], axis=1)
chrom_3_chri

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"41,115","46,104","16,168","41,101","80,514","13,35","33,105","24,86","1,23","48,82","3,5","8,72","5,13","86,96","1,95","33,191","1,0"
1,"91,65","86,64","115,69","72,70","391,203","30,18","105,33","54,56","13,11","102,28","6,2","49,31","10,8","139,43","28,68","154,70","1,0"
2,"144,12","117,33","166,18","120,22","558,36","33,15","132,6","91,19","21,3","118,12","6,2","79,1","16,2","172,10","54,42","183,41","1,0"
3,"34,122","42,108","81,103","75,67","277,317","3,45","82,56","52,58","11,13","85,45","6,2","35,45","5,13","91,91","26,70","104,120","1,0"
4,"89,67","58,92","115,69","45,97","331,263","45,3","48,90","48,62","9,15","52,78","2,6","46,34","12,6","77,105","54,42","155,69","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40182,"86,70","58,92","48,136","62,80","155,439","14,34","29,109","58,52","9,15","37,93","3,5","25,55","3,15","72,110","43,53","74,150","0,1"
40183,"126,30","141,9","165,19","137,5","549,45","37,11","122,16","109,1","23,1","121,9","6,2","74,6","17,1","172,10","55,41","211,13","0,1"
40184,"12,144","87,63","85,99","68,74","280,314","7,41","68,70","64,46","7,17","106,24","5,3","26,54","3,15","138,44","43,53","112,112","1,0"
40185,"94,62","116,34","119,65","100,42","342,252","26,22","78,60","79,31","16,8","93,37","6,2","54,26","10,8","110,72","77,19","119,105","0,1"
40186,"34,122","76,74","48,136","86,56","195,399","20,28","54,84","67,43","6,18","88,42","4,4","19,61","6,12","125,57","84,12","56,168","0,1"

In [47]:
chrom_3_chri.to_csv('/home/randomx/3_chri_complete.txt',index=False, sep=" ")

----------------------------------

## Heterochromatic

In [25]:
treemix_3L = pd.read_csv('/home/randomx/Scaricati/3L-het.allele_counts.txt.gz', sep = ' ')
treemix_3L

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"156,0","150,0","184,0","142,0","591,3","48,0","138,0","110,0","24,0","130,0",...,"79,1","17,1","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
1,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
2,"156,0","149,1","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
3,"156,0","150,0","180,4","142,0","592,2","48,0","137,1","110,0","24,0","127,3",...,"79,1","18,0","181,1","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
4,"156,0","138,12","178,6","135,7","594,0","48,0","138,0","104,6","23,1","127,3",...,"80,0","18,0","173,9","88,8","224,0","0,0","0,0","0,0","0,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4430,"156,0","127,23","183,1","134,8","592,2","48,0","138,0","93,17","24,0","129,1",...,"80,0","18,0","180,2","88,8","224,0","24,0","0,0","0,0","0,20","0,0"
4431,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","17,1","182,0","96,0","224,0","24,0","0,0","0,0","20,0","0,0"
4432,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","0,0","0,0","20,0","0,0"
4433,"156,0","150,0","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","0,0","0,0","20,0","0,0"
4434,"156,0","149,1","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"

In [18]:
treemix_3R = pd.read_csv('/home/randomx/Scaricati/3R-het.allele_counts.txt.gz', sep = ' ')
treemix_3R

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"156,0","150,0","184,0","142,0","594,0","46,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","181,1","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
1,"156,0","150,0","184,0","142,0","594,0","46,0","137,1","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
2,"156,0","150,0","184,0","142,0","594,0","46,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","178,0","96,0","223,1","24,0","0,0","8,0","20,0","20,0"
3,"156,0","150,0","184,0","142,0","594,0","46,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","221,3","24,0","1,0","8,0","20,0","20,0"
4,"156,0","150,0","184,0","142,0","593,1","46,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","181,1","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6706,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0",...,"79,1","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","0,0"
6707,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
6708,"156,0","150,0","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
6709,"156,0","150,0","184,0","142,0","591,3","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,24","0,0","8,0","20,0","20,0"
6710,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","223,1","24,0","1,0","8,0","20,0","20,0"

In [19]:
chrom_3 = pd.concat([treemix_3L, treemix_3R])
chrom_3

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"156,0","150,0","184,0","142,0","591,3","48,0","138,0","110,0","24,0","130,0",...,"79,1","17,1","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
1,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
2,"156,0","149,1","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
3,"156,0","150,0","180,4","142,0","592,2","48,0","137,1","110,0","24,0","127,3",...,"79,1","18,0","181,1","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
4,"156,0","138,12","178,6","135,7","594,0","48,0","138,0","104,6","23,1","127,3",...,"80,0","18,0","173,9","88,8","224,0","0,0","0,0","0,0","0,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6706,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0",...,"79,1","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","0,0"
6707,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
6708,"156,0","150,0","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
6709,"156,0","150,0","184,0","142,0","591,3","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,24","0,0","8,0","20,0","20,0"
6710,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","223,1","24,0","1,0","8,0","20,0","20,0"

In [20]:
chrom_3_chri = chrom_3.drop(chrom_3.columns[[16,18,19,20]], axis=1)
chrom_3_chri

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"156,0","150,0","184,0","142,0","591,3","48,0","138,0","110,0","24,0","130,0","8,0","79,1","17,1","182,0","96,0","224,0","0,0"
1,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","0,0"
2,"156,0","149,1","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","0,0"
3,"156,0","150,0","180,4","142,0","592,2","48,0","137,1","110,0","24,0","127,3","8,0","79,1","18,0","181,1","96,0","224,0","0,0"
4,"156,0","138,12","178,6","135,7","594,0","48,0","138,0","104,6","23,1","127,3","7,1","80,0","18,0","173,9","88,8","224,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6706,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","79,1","18,0","182,0","96,0","224,0","1,0"
6707,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
6708,"156,0","150,0","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
6709,"156,0","150,0","184,0","142,0","591,3","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","0,0"
6710,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","223,1","1,0"

----------------------------------
Filter missing SNPs

In [22]:
chrom_3_chri_filt = chrom_3_chri[chrom_3_chri.chri != '0,0']
chrom_3_chri_filt

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
46,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","79,1","18,0","182,0","96,0","224,0","1,0"
47,"156,0","150,0","182,2","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
48,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
171,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","88,8","224,0","0,1"
174,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6705,"156,0","149,1","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
6706,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","79,1","18,0","182,0","96,0","224,0","1,0"
6707,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
6708,"156,0","150,0","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
6710,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","223,1","1,0"

In [23]:
chrom_3_chri_filt.to_csv('/home/randomx/3_chri_het_filtered.txt',index=False, sep=" ")

---------------------------------------
# Chromosomal arm 3L

In [55]:
treemix_3L = pd.read_csv('/home/randomx/Scaricati/3L-complete.allele_counts.txt.gz', sep = ' ')
treemix_3L

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"156,0","150,0","184,0","142,0","591,3","48,0","138,0","110,0","24,0","130,0",...,"79,1","17,1","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
1,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
2,"156,0","149,1","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
3,"156,0","150,0","180,4","142,0","592,2","48,0","137,1","110,0","24,0","127,3",...,"79,1","18,0","181,1","96,0","224,0","0,0","0,0","0,0","0,0","0,0"
4,"156,0","138,12","178,6","135,7","594,0","48,0","138,0","104,6","23,1","127,3",...,"80,0","18,0","173,9","88,8","224,0","0,0","0,0","0,0","0,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32955,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
32956,"156,0","140,10","184,0","124,18","594,0","48,0","138,0","106,4","24,0","130,0",...,"80,0","18,0","178,4","96,0","224,0","24,0","0,0","8,0","20,0","20,0"
32957,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
32958,"156,0","150,0","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"79,1","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
32959,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","0,0","8,0","20,0","20,0"

In [58]:
chrom_3L_chri = treemix_3L.drop(treemix_3L.columns[[16,18,19,20]], axis=1)
chrom_3L_chri

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"156,0","150,0","184,0","142,0","591,3","48,0","138,0","110,0","24,0","130,0","8,0","79,1","17,1","182,0","96,0","224,0","0,0"
1,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","0,0"
2,"156,0","149,1","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","0,0"
3,"156,0","150,0","180,4","142,0","592,2","48,0","137,1","110,0","24,0","127,3","8,0","79,1","18,0","181,1","96,0","224,0","0,0"
4,"156,0","138,12","178,6","135,7","594,0","48,0","138,0","104,6","23,1","127,3","7,1","80,0","18,0","173,9","88,8","224,0","0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32955,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
32956,"156,0","140,10","184,0","124,18","594,0","48,0","138,0","106,4","24,0","130,0","8,0","80,0","18,0","178,4","96,0","224,0","0,0"
32957,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
32958,"156,0","150,0","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","79,1","18,0","182,0","96,0","224,0","1,0"
32959,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","0,0"

In [59]:
chrom_3L_chri = chrom_3L_chri[chrom_3L_chri.chri != '0,0']
chrom_3L_chri

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
46,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","79,1","18,0","182,0","96,0","224,0","1,0"
47,"156,0","150,0","182,2","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
48,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
171,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","88,8","224,0","0,1"
174,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32953,"156,0","150,0","184,0","141,1","594,0","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","0,1"
32954,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","126,4","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
32955,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
32957,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
32958,"156,0","150,0","183,1","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","79,1","18,0","182,0","96,0","224,0","1,0"

In [60]:
chrom_3L_chri.to_csv('/home/randomx/chrom_3L_chri.txt',index=False, sep=" ")

------------------
# Chromosomal arm 3R

In [61]:
treemix_3R = pd.read_csv('/home/randomx/Scaricati/3R-complete.allele_counts.txt.gz', sep = ' ')
treemix_3R

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"156,0","150,0","184,0","142,0","594,0","46,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","181,1","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
1,"156,0","150,0","184,0","142,0","594,0","46,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","178,0","96,0","223,1","24,0","0,0","8,0","20,0","20,0"
2,"155,1","150,0","184,0","142,0","594,0","46,0","138,0","109,1","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
3,"156,0","150,0","184,0","142,0","594,0","46,0","137,1","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
4,"156,0","138,12","10,174","135,7","31,563","0,46","20,118","105,5","1,23","33,97",...,"3,77","1,17","60,122","89,7","7,217","24,0","1,0","8,0","20,0","20,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46890,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0",...,"79,1","18,0","182,0","96,0","222,2","24,0","1,0","8,0","20,0","20,0"
46891,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","129,1",...,"80,0","18,0","178,4","96,0","223,1","24,0","1,0","8,0","20,0","20,0"
46892,"156,0","150,0","184,0","142,0","589,5","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","220,4","24,0","1,0","8,0","20,0","20,0"
46893,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0",...,"80,0","18,0","182,0","96,0","224,0","24,0","1,0","8,0","20,0","20,0"
46894,"156,0","129,21","173,11","122,20","538,56","48,0","131,7","102,8","21,3","102,28",...,"71,9","17,1","137,45","96,0","199,25","0,24","0,1","0,8","0,20","0,20"

In [62]:
chrom_3R_chri = treemix_3R.drop(treemix_3R.columns[[16,18,19,20]], axis=1)
chrom_3R_chri

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"156,0","150,0","184,0","142,0","594,0","46,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","181,1","96,0","224,0","1,0"
1,"156,0","150,0","184,0","142,0","594,0","46,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","178,0","96,0","223,1","0,0"
2,"155,1","150,0","184,0","142,0","594,0","46,0","138,0","109,1","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
3,"156,0","150,0","184,0","142,0","594,0","46,0","137,1","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
4,"156,0","138,12","10,174","135,7","31,563","0,46","20,118","105,5","1,23","33,97","8,0","3,77","1,17","60,122","89,7","7,217","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46890,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","79,1","18,0","182,0","96,0","222,2","1,0"
46891,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","129,1","8,0","80,0","18,0","178,4","96,0","223,1","1,0"
46892,"156,0","150,0","184,0","142,0","589,5","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","220,4","1,0"
46893,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
46894,"156,0","129,21","173,11","122,20","538,56","48,0","131,7","102,8","21,3","102,28","7,1","71,9","17,1","137,45","96,0","199,25","0,1"

In [63]:
chrom_3R_chri = chrom_3R_chri[chrom_3R_chri.chri != '0,0']
chrom_3R_chri

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"156,0","150,0","184,0","142,0","594,0","46,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","181,1","96,0","224,0","1,0"
2,"155,1","150,0","184,0","142,0","594,0","46,0","138,0","109,1","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
3,"156,0","150,0","184,0","142,0","594,0","46,0","137,1","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
4,"156,0","138,12","10,174","135,7","31,563","0,46","20,118","105,5","1,23","33,97","8,0","3,77","1,17","60,122","89,7","7,217","1,0"
5,"156,0","150,0","184,0","142,0","593,1","46,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46890,"156,0","150,0","184,0","142,0","594,0","48,0","138,0","110,0","24,0","130,0","8,0","79,1","18,0","182,0","96,0","222,2","1,0"
46891,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","129,1","8,0","80,0","18,0","178,4","96,0","223,1","1,0"
46892,"156,0","150,0","184,0","142,0","589,5","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","220,4","1,0"
46893,"156,0","150,0","184,0","142,0","593,1","48,0","138,0","110,0","24,0","130,0","8,0","80,0","18,0","182,0","96,0","224,0","1,0"
46894,"156,0","129,21","173,11","122,20","538,56","48,0","131,7","102,8","21,3","102,28","7,1","71,9","17,1","137,45","96,0","199,25","0,1"

In [64]:
chrom_3R_chri.to_csv('/home/randomx/chrom_3R_chri.txt',index=False, sep=" ")

--------------------------
# Chromosomal arm 3L - Euchromatic

In [67]:
treemix_3L_eu = pd.read_csv('/home/randomx/Dropbox/Ag1000G_carlo/paper1/scripts/treemix-data/phase2_with_outgroups/3L_free/3L-free.allele_counts.txt.gz', sep = ' ')
treemix_3L_eu

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"41,115","46,104","16,168","41,101","80,514","13,35","33,105","24,86","1,23","48,82",...,"8,72","5,13","86,96","1,95","33,191","0,24","1,0","8,0","20,0","20,0"
1,"91,65","86,64","115,69","72,70","391,203","30,18","105,33","54,56","13,11","102,28",...,"49,31","10,8","139,43","28,68","154,70","0,24","1,0","8,0","5,15","20,0"
2,"144,12","117,33","166,18","120,22","558,36","33,15","132,6","91,19","21,3","118,12",...,"79,1","16,2","172,10","54,42","183,41","24,0","1,0","8,0","20,0","20,0"
3,"34,122","42,108","81,103","75,67","277,317","3,45","82,56","52,58","11,13","85,45",...,"35,45","5,13","91,91","26,70","104,120","24,0","1,0","8,0","20,0","20,0"
4,"89,67","58,92","115,69","45,97","331,263","45,3","48,90","48,62","9,15","52,78",...,"46,34","12,6","77,105","54,42","155,69","24,0","1,0","8,0","20,0","20,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27604,"88,68","60,90","93,91","39,103","311,283","42,6","94,44","47,63","10,14","52,78",...,"32,48","11,7","67,115","72,24","99,125","24,0","0,1","0,8","0,20","0,20"
27605,"104,52","139,11","176,8","136,6","564,30","43,5","128,10","106,4","23,1","121,9",...,"77,3","16,2","176,6","92,4","206,18","24,0","1,0","8,0","20,0","20,0"
27606,"134,22","106,44","102,82","85,57","300,294","21,27","68,70","68,42","14,10","70,60",...,"40,40","10,8","97,85","37,59","119,105","0,24","0,1","0,8","0,20","20,0"
27607,"27,129","74,76","74,110","81,61","234,360","27,21","32,106","44,66","12,12","61,69",...,"28,52","6,12","101,81","35,61","104,120","24,0","1,0","0,8","0,20","0,20"
27608,"143,13","137,13","141,43","134,8","458,136","39,9","121,17","103,7","18,6","123,7",...,"63,17","13,5","159,23","72,24","170,54","14,10","1,0","8,0","20,0","20,0"

In [68]:
chrom_3L_chri_eu = treemix_3L_eu.drop(treemix_3L_eu.columns[[16,18,19,20]], axis=1)
chrom_3L_chri_eu

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"41,115","46,104","16,168","41,101","80,514","13,35","33,105","24,86","1,23","48,82","3,5","8,72","5,13","86,96","1,95","33,191","1,0"
1,"91,65","86,64","115,69","72,70","391,203","30,18","105,33","54,56","13,11","102,28","6,2","49,31","10,8","139,43","28,68","154,70","1,0"
2,"144,12","117,33","166,18","120,22","558,36","33,15","132,6","91,19","21,3","118,12","6,2","79,1","16,2","172,10","54,42","183,41","1,0"
3,"34,122","42,108","81,103","75,67","277,317","3,45","82,56","52,58","11,13","85,45","6,2","35,45","5,13","91,91","26,70","104,120","1,0"
4,"89,67","58,92","115,69","45,97","331,263","45,3","48,90","48,62","9,15","52,78","2,6","46,34","12,6","77,105","54,42","155,69","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27604,"88,68","60,90","93,91","39,103","311,283","42,6","94,44","47,63","10,14","52,78","3,5","32,48","11,7","67,115","72,24","99,125","0,1"
27605,"104,52","139,11","176,8","136,6","564,30","43,5","128,10","106,4","23,1","121,9","6,2","77,3","16,2","176,6","92,4","206,18","1,0"
27606,"134,22","106,44","102,82","85,57","300,294","21,27","68,70","68,42","14,10","70,60","5,3","40,40","10,8","97,85","37,59","119,105","0,1"
27607,"27,129","74,76","74,110","81,61","234,360","27,21","32,106","44,66","12,12","61,69","6,2","28,52","6,12","101,81","35,61","104,120","1,0"
27608,"143,13","137,13","141,43","134,8","458,136","39,9","121,17","103,7","18,6","123,7","6,2","63,17","13,5","159,23","72,24","170,54","1,0"

In [70]:
chrom_3L_chri_eu = chrom_3L_chri_eu[chrom_3L_chri_eu.chri != '0,0']
chrom_3L_chri_eu

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"41,115","46,104","16,168","41,101","80,514","13,35","33,105","24,86","1,23","48,82","3,5","8,72","5,13","86,96","1,95","33,191","1,0"
1,"91,65","86,64","115,69","72,70","391,203","30,18","105,33","54,56","13,11","102,28","6,2","49,31","10,8","139,43","28,68","154,70","1,0"
2,"144,12","117,33","166,18","120,22","558,36","33,15","132,6","91,19","21,3","118,12","6,2","79,1","16,2","172,10","54,42","183,41","1,0"
3,"34,122","42,108","81,103","75,67","277,317","3,45","82,56","52,58","11,13","85,45","6,2","35,45","5,13","91,91","26,70","104,120","1,0"
4,"89,67","58,92","115,69","45,97","331,263","45,3","48,90","48,62","9,15","52,78","2,6","46,34","12,6","77,105","54,42","155,69","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27604,"88,68","60,90","93,91","39,103","311,283","42,6","94,44","47,63","10,14","52,78","3,5","32,48","11,7","67,115","72,24","99,125","0,1"
27605,"104,52","139,11","176,8","136,6","564,30","43,5","128,10","106,4","23,1","121,9","6,2","77,3","16,2","176,6","92,4","206,18","1,0"
27606,"134,22","106,44","102,82","85,57","300,294","21,27","68,70","68,42","14,10","70,60","5,3","40,40","10,8","97,85","37,59","119,105","0,1"
27607,"27,129","74,76","74,110","81,61","234,360","27,21","32,106","44,66","12,12","61,69","6,2","28,52","6,12","101,81","35,61","104,120","1,0"
27608,"143,13","137,13","141,43","134,8","458,136","39,9","121,17","103,7","18,6","123,7","6,2","63,17","13,5","159,23","72,24","170,54","1,0"

In [71]:
chrom_3L_chri_eu.to_csv('/home/randomx/chrom_3L_chri_eu.txt',index=False, sep=" ")

-----------------------------
# Chromosomal arm 3R euchromatic

In [72]:
treemix_3R_eu = pd.read_csv('/home/randomx/Dropbox/Ag1000G_carlo/paper1/scripts/treemix-data/phase2_with_outgroups/3R_free/3R-free.allele_counts.txt.gz', sep = ' ')
treemix_3R_eu

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,...,GNgam,GQgam,GW,KE,UGgam,arab,chri,mela,meru,quad
0,"118,38","106,44","51,133","83,59","174,420","22,26","27,111","58,52","10,14","31,99",...,"26,54","12,6","44,138","89,7","50,174","0,24","0,1","0,8","0,20","0,20"
1,"5,151","109,41","78,106","91,51","253,341","22,26","23,115","73,37","7,17","65,65",...,"25,55","4,14","88,94","30,66","77,147","0,24","0,1","0,8","0,20","0,20"
2,"29,127","46,104","70,114","40,102","231,363","26,22","14,124","31,79","13,11","32,98",...,"40,40","11,7","34,148","37,59","77,147","0,24","0,1","0,8","0,20","0,20"
3,"113,43","117,33","161,23","114,28","513,81","3,45","121,17","88,22","18,6","115,15",...,"75,5","14,4","162,20","37,59","179,45","24,0","0,1","8,0","20,0","20,0"
4,"84,72","103,47","104,80","106,36","331,263","17,31","75,63","87,23","16,8","79,51",...,"50,30","11,7","106,76","89,7","122,102","24,0","1,0","8,0","20,0","20,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40182,"86,70","58,92","48,136","62,80","155,439","14,34","29,109","58,52","9,15","37,93",...,"25,55","3,15","72,110","43,53","74,150","0,24","0,1","0,8","0,20","0,20"
40183,"126,30","141,9","165,19","137,5","549,45","37,11","122,16","109,1","23,1","121,9",...,"74,6","17,1","172,10","55,41","211,13","24,0","0,1","0,8","20,0","20,0"
40184,"12,144","87,63","85,99","68,74","280,314","7,41","68,70","64,46","7,17","106,24",...,"26,54","3,15","138,44","43,53","112,112","2,22","1,0","0,8","20,0","20,0"
40185,"94,62","116,34","119,65","100,42","342,252","26,22","78,60","79,31","16,8","93,37",...,"54,26","10,8","110,72","77,19","119,105","2,22","0,1","8,0","20,0","20,0"
40186,"34,122","76,74","48,136","86,56","195,399","20,28","54,84","67,43","6,18","88,42",...,"19,61","6,12","125,57","84,12","56,168","4,20","0,1","8,0","20,0","20,0"

In [73]:
chrom_3R_chri_eu = treemix_3R_eu.drop(treemix_3R_eu.columns[[16,18,19,20]], axis=1)
chrom_3R_chri_eu

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"118,38","106,44","51,133","83,59","174,420","22,26","27,111","58,52","10,14","31,99","4,4","26,54","12,6","44,138","89,7","50,174","0,1"
1,"5,151","109,41","78,106","91,51","253,341","22,26","23,115","73,37","7,17","65,65","6,2","25,55","4,14","88,94","30,66","77,147","0,1"
2,"29,127","46,104","70,114","40,102","231,363","26,22","14,124","31,79","13,11","32,98","5,3","40,40","11,7","34,148","37,59","77,147","0,1"
3,"113,43","117,33","161,23","114,28","513,81","3,45","121,17","88,22","18,6","115,15","4,4","75,5","14,4","162,20","37,59","179,45","0,1"
4,"84,72","103,47","104,80","106,36","331,263","17,31","75,63","87,23","16,8","79,51","5,3","50,30","11,7","106,76","89,7","122,102","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40182,"86,70","58,92","48,136","62,80","155,439","14,34","29,109","58,52","9,15","37,93","3,5","25,55","3,15","72,110","43,53","74,150","0,1"
40183,"126,30","141,9","165,19","137,5","549,45","37,11","122,16","109,1","23,1","121,9","6,2","74,6","17,1","172,10","55,41","211,13","0,1"
40184,"12,144","87,63","85,99","68,74","280,314","7,41","68,70","64,46","7,17","106,24","5,3","26,54","3,15","138,44","43,53","112,112","1,0"
40185,"94,62","116,34","119,65","100,42","342,252","26,22","78,60","79,31","16,8","93,37","6,2","54,26","10,8","110,72","77,19","119,105","0,1"
40186,"34,122","76,74","48,136","86,56","195,399","20,28","54,84","67,43","6,18","88,42","4,4","19,61","6,12","125,57","84,12","56,168","0,1"

In [74]:
chrom_3R_chri_eu = chrom_3R_chri_eu[chrom_3R_chri_eu.chri != '0,0']
chrom_3R_chri_eu

,AOcol,BFcol,BFgam,CIcol,CMgam,FRgam,GAgam,GHcol,GHgam,GM,GNcol,GNgam,GQgam,GW,KE,UGgam,chri
0,"118,38","106,44","51,133","83,59","174,420","22,26","27,111","58,52","10,14","31,99","4,4","26,54","12,6","44,138","89,7","50,174","0,1"
1,"5,151","109,41","78,106","91,51","253,341","22,26","23,115","73,37","7,17","65,65","6,2","25,55","4,14","88,94","30,66","77,147","0,1"
2,"29,127","46,104","70,114","40,102","231,363","26,22","14,124","31,79","13,11","32,98","5,3","40,40","11,7","34,148","37,59","77,147","0,1"
3,"113,43","117,33","161,23","114,28","513,81","3,45","121,17","88,22","18,6","115,15","4,4","75,5","14,4","162,20","37,59","179,45","0,1"
4,"84,72","103,47","104,80","106,36","331,263","17,31","75,63","87,23","16,8","79,51","5,3","50,30","11,7","106,76","89,7","122,102","1,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40182,"86,70","58,92","48,136","62,80","155,439","14,34","29,109","58,52","9,15","37,93","3,5","25,55","3,15","72,110","43,53","74,150","0,1"
40183,"126,30","141,9","165,19","137,5","549,45","37,11","122,16","109,1","23,1","121,9","6,2","74,6","17,1","172,10","55,41","211,13","0,1"
40184,"12,144","87,63","85,99","68,74","280,314","7,41","68,70","64,46","7,17","106,24","5,3","26,54","3,15","138,44","43,53","112,112","1,0"
40185,"94,62","116,34","119,65","100,42","342,252","26,22","78,60","79,31","16,8","93,37","6,2","54,26","10,8","110,72","77,19","119,105","0,1"
40186,"34,122","76,74","48,136","86,56","195,399","20,28","54,84","67,43","6,18","88,42","4,4","19,61","6,12","125,57","84,12","56,168","0,1"

In [75]:
chrom_3R_chri_eu.to_csv('/home/randomx/chrom_3R_chri_eu.txt',index=False, sep=" ")